# Configuración de la versión de Netlify
[build]
  base = "dist"  # Directorio de salida de Vite
  command = "npm run build"  # Comando para construir tu aplicación Vite
  publish = "dist"  # Directorio de publicación

# Configuración de redirecciones para una SPA (Single Page Application)
[[redirects]]
  from = "/*"  # Todas las solicitudes
  to = "/index.html"  # Redirige a index.html
  status = 200  # Código de respuesta 200 (OK)
